name: Hello World Workflow

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the repository code

      - name: Echo Hello World
        run: echo "Hello, World!"
